version: '3.4'

services:
  supermongo:
    image: mongo:4
    environment:
      - MONGO_INITDB_DATABASE=mabellebase
    volumes:
      - ./:/docker-entrypoint-initdb.d:ro
    restart: always
    ports:
      - 27017:27017